const ArunachalPradeshData =[
    {
        id:"1",
        city:"Itanagar",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"2",
        city:"Balijan",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"3",
        city:"Donyi-Polo",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"4",
        city:"Banderdewa",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"5",
        city:"Doimukh",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },

];


export default ArunachalPradeshData