const BiharData =[
    {
        id:"1",
        city:"Patna",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"2",
        city:"Gaya",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"3",
        city:"Bhagalpur",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"4",
        city:"Muzaffarpur",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },
    {
        id:"5",
        city:"Siwan",
        nameOfFacility:"",
        address: "near Subhash Nagar mall",
        contact: "8766357982",
        avalability: "Oxygen cylinders Pre-booking and payment must be done today itself",
        price:"50k Advance payment Pick up yourself.",
        comments:"May reach teh place directly for refilling, charges are rs 200 for 10 kg",
        VerficationDataTime :"",
    },

];


export default BiharData